### ISSUE TITLE
Module not found flocker and kubernetes 

### ISSUE THREAD

**Issue by hoannv46** [openvstorage/openvstorage-flocker-driver#3]
Hi all.
I current install flocker and kubernetes.
I install flocker and openvstorage-flocker-driver but i don't have module named volumedriver.storagerouter.storagerouterclient.
How i can install this module in flocker python lib.

> File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n    backend_and_api_args_from_configuration\n    backend = backend_loader.get(backend_name)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/plugin.py\", line 128, in get\n    plugin_module = namedAny(plugin_name)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/python/reflect.py\", line 303, in namedAny\n    topLevelPackage = _importAndCheckStack(trialname)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/python/reflect.py\", line 250, in _importAndCheckStack\n    reraise(excValue, excTraceback)\n  File \"build/bdist.linux-x86_64/egg/openvstorage_flocker_plugin/__init__.py\", line 15, in <module>\n    \n  File \"build/bdist.linux-x86_64/egg/openvstorage_flocker_plugin/openvstorage_blockdevice.py\", line 25, in <module>\n    \nexceptions.ImportError: No module named volumedriver.storagerouter.storagerouterclient\n", "message_type": "twisted:log", "task_level": [1]}

Thanks

**Comment by hoannv46** [comment]
I install package volumedriver-server.x86_64 and add environment for flocker-dataset-agent.service.
I pass no module but file config not 

> Failed to open config file arakoon://config/ovs/vpools/dfb29087-24dd-464e-bf91-740b34a263ac/hosts/vpooldemo3pexFl75D8h1vLju/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini\n

This file removed in new version openvstorage.?
Thanks.

**Comment by wimpers** [comment]
I know @kinvaris was able to set it up correctly, see https://github.com/openvstorage/openvstorage-flocker-driver/issues/2  . I hope that one helps?

**Comment by hoannv46** [comment]
Yes. This help me alot of.

**Comment by wimpers** [comment]
I believe you will need to copy /opt/OpenvStorage/config/arakoon_cacc.ini from one of the  nodes with the volumedriver to the node where you get this error.

**Comment by hoannv46** [comment]
I copy file arakoon_cacc.ini to server flocker. 
I installed volume driver and config PATH then no error import moule.
it still error
> [root@k8s-minion1 openvstorage_flocker_plugin]# ls -l /opt/OpenvStorage/config/
total 4
-rw-r--r-- 1 root root 401 Mar 23 06:25 arakoon_cacc.ini
drwxr-xr-x 2 root root  28 Mar 23 03:50 templates

**Comment by wimpers** [comment]
New flocker plugin is available which uses the edge.
